export const DEFAULTS = {
  padding: 20,
  sourceStubLength: 20,
  targetStubLength: 20,
  bendPenalty: 1,
  nodeWidth: 150,
  nodeHeight: 60,
  edgeStrokeColor: '#555',
  edgeStrokeWidth: 1.5,
  edgeSeparation: 5,
  bendRadius: 8,
  horizontalGap: 40,
  verticalGap: 60,
  perBranchCollapse: false,
  collapseAnimation: true,
};
