export const DEFAULTS = {
    padding: 22,
    sourceStubLength: 20,
    targetStubLength: 20,
    bendPenalty: 100,
    earlyBendBias: 0.01,
    nodeWidth: 80,
    nodeHeight: 80,
    edgeStrokeColor: "#555",
    edgeStrokeWidth: 1.5,
    edgeSeparation: 5,
    bendRadius: 8,
    horizontalGap: 48,
    verticalGap: 48,
    verticalGapWithLabel: 80,
    perBranchCollapse: false,
    collapseAnimation: true,
    edgeLabelFontSize: 11,
    edgeLabelOffset: 4,
    edgeLabelBackground: "#ffffff",
    edgeSelectedColor: "#1976d2",
    edgeSelectedWidth: 2.5,
    addButtonVerticalOffset: 20,
    addButtonRightOffset: null,
    addButtonSize: 30,
};
